# Generated by Django 5.0.3 on 2024-04-05 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_name', models.CharField(choices=[('diesal', 'diesal'), ('petrol', 'petrol'), ('cng', 'cng')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Carmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(choices=[('maruthi', 'maruthi'), ('toyata', 'toyata')], max_length=100)),
                ('fuel_name', models.ManyToManyField(to='app.fuelmodel')),
            ],
        ),
    ]
